version: '3.1'
services:
  ubuntu:
    build:
      context: ./
    container_name: ubuntu
    tty: true
    volumes:
      #mkdir -p ./ubuntu && chmod -R 775 ./ubuntu && umask 0002
      - ./ubuntu/ansible:/etc/ansible
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
