version: '3.1'
services:
  ubuntu:
    build:
      context: ./
    container_name: ubuntu
    hostname: ubuntu
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ubuntu/conf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
