version: '3.1'
services:
  ubuntu:
    build:
      context: ./
    container_name: ubuntu
    hostname: ubuntu
    tty: true
    volumes:
      #mkdir -p ./data && chmod -R 775 ./data && umask 0002
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
